server:
  port: 9094

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: PATIENT
          uri: lb://PATIENT
          predicates:
            - Path=/patient/**

        - id: DOCTOR
          uri: lb://DOCTOR
          predicates:
            - Path=/doctor/**

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true

